apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "remindapp.fullname" . }}
  labels:
    {{- include "remindapp.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      path: /metrics
  selector:
    matchLabels:
      {{- include "remindapp.selectorLabels" . | nindent 6 }}
